kind: pipeline
name: default

steps:
  - name: vet
    image: golang:1.11-stretch
    pull: always
    commands:
      - go mod tidy
      - go vet ./...
  - name: test
    image: golang:1.11-stretch
    pull: always
    commands:
      - go mod tidy
      - go test -cover ./...
